### ISSUE TITLE
Unknown type name 'namespace'

### ISSUE THREAD

**Issue by calitb** [IvySpace-Dev/react-native-zoom#7]
I am trying to use this but I end up with a `Unknown type name 'namespace'` error.

Running Xcode 10.1 

![screen shot 2019-02-27 at 10 38 09 am](https://user-images.githubusercontent.com/1728291/53502320-d0cd1380-3a7b-11e9-8c42-0c21d16779fd.png)

**Comment by iamsteeve** [comment]
how did you fix it? :o

**Comment by harshit-prog** [comment]
yes, how you guys fix it?

**Comment by harshit-prog** [comment]
> how did you fix it? :o

have you got any solution?
